# Generated by Django 3.2.4 on 2021-06-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idName', models.SlugField(max_length=100, unique=True)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('fromTime', models.CharField(max_length=10)),
                ('toTime', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=2)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
