# Generated by Django 3.2.4 on 2021-06-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
