# Generated by Django 3.2.4 on 2021-06-19 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_food_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderCost', models.IntegerField()),
                ('ApproximateArrivalTime', models.DateTimeField()),
                ('state', models.CharField(choices=[('AWAITING_APPROVAL', 'Awaiting Approval'), ('PREPARING', 'Preparing'), ('SENDING', 'Sending'), ('DELIVERED', 'Delivered')], max_length=100)),
                ('Food', models.ManyToManyField(to='restaurant.Food')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
