# Generated by Django 3.2.4 on 2021-06-19 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
