# Generated by Django 3.2.4 on 2021-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='RestaurantComment',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
