# Generated by Django 3.2.4 on 2021-06-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_comment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order'),
        ),
    ]
