# Generated by Django 3.2.4 on 2021-06-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_comment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Order',
        ),
    ]
